spring:
  datasource:
    url: jdbc:postgresql://3.34.252.182:5432/postgres
    password: dlduwls0822!
    driver-class-name: org.postgresql.Driver
    username: postgres
#    url: jdbc:postgresql://localhost:5432/postgres
#    password: 1018
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  cache:
    type: redis
  redis:
    host: 3.34.252.182
#    host: localhost
    port: 6379
server:
  port: 443
#  HTTPS SSL를 시도했던 흔적들
#  ssl:
#    enabled: true
#    key-store: fpkeystore.pkcs12
#    key-store-type: PKCS12
#    key-store-password: 'dlduwls0822!'
#    key-password: 'dlduwls0822!'
jwt:
  token:
    header: Authorization
    issuer: Flare_Point
    clientSecret: aa64eb33e4701c204be9ca4b16c488eee31ae31cb561b1f5f50f6c7b63d14cb1
    expirySeconds: 10800